package br.com.sayurienterprise.photostore.model

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.io.Serializable

@Entity(tableName = "photo_table")
data class Photo(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    var name: String,
    var age: Int,
    var date: String,
    var photoFileName: String
) : Serializable {

//Don´t need to create getters and setters. Automatically generated by kotlin.

    override fun toString(): String {
        return "PhotoId: $id, Nome: $name, Idade: $age, Data: $date, Nome do Arquivo: $photoFileName"
    }

}
